services:
  db:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
  web:
    ports:
      - "3000:3000"
  backend:
    ports:
      - "4000:4000"
  redis_adminer:
    ports:
      - "5540:5540"
